<?php

use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        Schema::create('pos', function (Blueprint $table) {
            // generated by brand
            $table->id();
            $table->foreignId('order_id')->constrained();
            $table->foreignId('party_id')->constrained();
            $table->foreignId('product_id')->constrained();
            $table->foreignId('material_id')->constrained();
            $table->string('name')->nullable();

            // generated by brand for monaal
            $table->string('m_customer_id')->nullable(); // brand this->order->ledger->party_id
            $table->string('m_customer_name')->nullable(); // brand this->order->ledger->party_id
            $table->string('m_product_id')->nullable(); // brand this->order->leder->product->materials->eachId 
            $table->string('m_order_id')->nullable(); // brand this->order->sid
            $table->string('m_catelog_id')->nullable(); // brand this->order->ledger->product_id
            $table->string('status')->default('draft'); // 'draft','issued','progress','completed','cancelled'
            $table->timestamp('accepted_at')->default(DB::raw('CURRENT_TIMESTAMP'));
            $table->float('order_quantity')->default(0); // brand order->quantity

            // generated by monaal for brand
            $table->string('sid')->nullable(); // so number
            $table->boolean('pre_order')->default(false);
            $table->float('rate')->default(0);
            $table->float('quantity')->default(0); // sum of all so_items
            $table->float('amount', 12)->default(0); // sum of all so_items * rate
            $table->longText('note')->nullable();
            $table->string('issued_by')->nullable();
            $table->timestamp('issued_at')->nullable();
            $table->string('completed_by')->nullable();
            $table->timestamp('completed_at')->nullable();
            $table->string('delivery_mode')->default('free delivery');
            $table->tinyInteger('expiry')->default(6);
            $table->tinyInteger('tol_rate')->default('0');
            $table->tinyInteger('tol_quantity')->default('0');
            $table->tinyInteger('tol_expiry')->default('0');
            $table->text('payment_terms')->nullable();
            $table->text('rejection_terms')->nullable();
            $table->text('special_terms')->nullable();
            $table->boolean('archived')->default(false);
            $table->text('reason')->nullable();
            $table->text('uuid')->nullable();
            $table->timestamps();
        });
        
        Schema::create('po_items', function (Blueprint $table) {
            // generated by brand 
            $table->id();
            $table->foreignId('po_id')->constrained(); 
            $table->foreignId('material_option_id')->constrained();
            $table->foreignId('material_range_id')->constrained();
            $table->unique(['po_id', 'material_option_id', 'material_range_id']);
            // generated by brand for monaal
            $table->string('product_option_id')->nullable(); // brand material_option_id
            $table->string('product_range_id')->nullable(); // brand material_range_id
            $table->float('order_quantity')->default(0); // brand->order->quantity 
            $table->float('fcpu')->default(1); // fabric consumption per unit
            $table->float('quantity')->default(0); // brand->order->quantity x fcpu
            $table->float('rate')->default(0); // brand materialRange->price
            $table->float('amount', 12)->default(0); // quantity x rate

            // generated by monaal for brand
            $table->string('so_id')->nullable();
            $table->string('note')->nullable();
            $table->string('name')->nullable();
            $table->timestamps();
        });

        Schema::create('monaal_bills', function (Blueprint $table) {
            $table->id();
            $table->string('monaal_id')->nullable();
            $table->string('uuid')->nullable();
            $table->string('doc_no')->nullable();
            $table->date('doc_date')->nullable();
            $table->string('customer_sid')->nullable();
            $table->string('status')->default('draft'); // 'draft','completed','paid'
            $table->text('note')->nullable();
            $table->float('amount', 15)->default(0);
            $table->float('payable', 15)->default(0);
            $table->float('balance', 15)->default(0);
            $table->text('tags')->nullable();
            $table->string('completed_by')->nullable();
            $table->timestamp('completed_at')->nullable();
            $table->timestamp('paid_at')->nullable();
            $table->json('details')->nullable();
            $table->json('pos')->nullable();
            $table->timestamps();
        });
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::dropIfExists('po_items');
        Schema::dropIfExists('pos');
        Schema::dropIfExists('monaal_bills');
    }
};
